spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
email: 
  account: 410882981@qq.com
  oauthCode: lxvoduzwzzxlbibc
gateway: 
  duration: 60
  limit: 3
